name: Airspace Monitor

on:
  schedule:
    - cron: '*/15 * * * *'  # Запуск каждые 15 минут
  workflow_dispatch:        # Позволяет запускать мониторинг вручную

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Разрешение на запись для обновления state.json

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Analysis
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}      # Секрет с токеном бота
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}  # Секрет с ID чата
        run: python main.py

      - name: Commit State
        run: |
          git config --global user.name "Airspace-Bot"
          git config --global user.email "bot@github.com"
          git add state.json
          git commit -m "Update state: $(date)" || echo "No changes to commit"
          git push
